apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - port: 20
      targetPort: 20
      name: ftp-data
      protocol: TCP
    - port: 21
      targetPort: 21
      name: ftp
      protocol: TCP
    - port: 30000
      targetPort: 30000
      name: passive0
      protocol: TCP
    - port: 30001
      targetPort: 30001
      name: passive1
      protocol: TCP
    - port: 30002
      targetPort: 30002
      name: passive2
      protocol: TCP
    - port: 30003
      targetPort: 30003
      name: passive3
      protocol: TCP
    - port: 30004
      targetPort: 30004
      name: passive4
      protocol: TCP
  loadBalancerIP: 172.17.0.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: juyang_ftps
          imagePullPolicy: Never
          ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 30000
            - containerPort: 30001
            - containerPort: 30002
            - containerPort: 30003
            - containerPort: 30004
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            tcpSocket:
              port: 21
