apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  ports:
    - port: 35000
      targetPort: 35000
      protocol: TCP
  selector:
    app: telegraf
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: juyang_telegraf
          imagePullPolicy: Never
          ports:
            - containerPort: 35000
          volumeMounts:
            - name: telegraf-endpoint
              mountPath: /var/run/docker.sock
      volumes:
        - name: telegraf-endpoint
          hostPath:
            path: /var/run/docker.sock
            type: Socket
